services:
#############################################      
#              SPARK CLUSTER                #
#############################################
  spark-master:
    image: spark_cluster:latest
    container_name: spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
    environment:
      - SPARK_WORKLOAD=master
    volumes:
      - shared_data:/opt/spark
      - ./data:/opt/spark/data

  spark-worker-1:
    image: spark_cluster:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=worker
    volumes:
      - shared_data:/opt/spark
      - ./data:/data

#############################################
#               ZEPPELIN                    #
#############################################
  zeppelin:
    image: apache/zeppelin:0.11.2
    container_name: zeppelin
    ports:
      - "8080:8080"
    volumes:
      - shared_data:/zeppelin/spark
      - ./notebooks:/opt/zeppelin/notebook
      - ./data:/data
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_HOME=/zeppelin/spark
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
volumes:
  shared_data: